### ISSUE TITLE
Write Proper Documentation for Booklee.

### ISSUE THREAD

**Issue by Rajdip019** [Rajdip019/booklee#39]
Here is how Booklee works.

[https://rajdeepsengupta.notion.site/Project-Details-0fcfce9964da4e96af6564c87aa631fc](url)

1. What is Booklee?
2. All features available.
2. How to run it in local environment?
3. About API used and API keys.
4. All contributors section.

**Comment by PreetSangha** [comment]
Hi there. I just noticed the link is entitled https://rajdeepsengupta.notion.site while it actually points to https://github.com/Rajdip019/booklee/issues/url.

**Comment by AryanGodara** [comment]
Hey! I am starting to write the documentation. I will update you as I go along.
UPDATE: You already have "Project Details", so is it okay, if I just convert that to a documentation.md file ?

**Comment by Rajdip019** [comment]
Thank You for adding Documentation @AryanGodara .

**Comment by AryanGodara** [comment]
> Thank You for adding Documentation @AryanGodara .

I'll try to complete the rest of the documentation today by EOD (IST)

**Comment by Rajdip019** [comment]
> 

That's sound amazing!!
