### ISSUE TITLE
Api Documentation 

### ISSUE THREAD

**Issue by Debajyoti14** [Rajdip019/booklee#48]
##Api used in the project##

1. Azure Cognitive Search
2. Mapbox API
3. GeoCoding API
4. GeoLocation API
5. And used azure cosmos dB for database

@AryanGodara 
We will be happy if you add this section in the documentation.

**Comment by AryanGodara** [comment]
> ##Api used in the project##
> 
> 1. Azure Cognitive Search
> 2. Mapbox API
> 3. GeoCoding API
> 4. GeoLocation API
> 5. And used azure cosmos dB for database
> 
> @AryanGodara 
> We will be happy if you add this section in the documentation.

Yes, I'll do it

**Comment by Rajdip019** [comment]
Thanks @AryanGodara , it's Done.
